import {describe,expect,it} from "vitest";import {MatchingEngine,seededBook,summarize} from "../lib/matching-engine";import fixture from "../../tests/fixtures/parity.json";
describe("price-time matching engine",()=>{
  it("reports best prices and cancels resting orders",()=>{const book=seededBook();const view=summarize(book);expect(view.bestBid).toBe(99.75);expect(view.bestAsk).toBe(100.25);expect(book.cancel(view.snapshot.bids[0].orderId)).toBe(true)});
  it("matches multiple levels at maker prices",()=>{const book=new MatchingEngine();book.submit({side:"sell",quantity:4,price:100,orderId:"first"});book.submit({side:"sell",quantity:3,price:101,orderId:"second"});const result=book.submit({side:"buy",quantity:6,price:102,orderId:"taker"});expect(result.fills.map(t=>[t.price,t.quantity])).toEqual([[100,4],[101,2]]);expect(book.snapshot().asks[0].remaining).toBe(1)});
  it("preserves time priority and partial fills",()=>{const book=new MatchingEngine();book.submit({side:"sell",quantity:3,price:100,orderId:"early"});book.submit({side:"sell",quantity:3,price:100,orderId:"late"});book.submit({side:"buy",quantity:4,orderType:"market",orderId:"market"});expect(book.trades.map(t=>t.maker)).toEqual(["early","late"]);expect(book.snapshot().asks[0].remaining).toBe(2)});
  it("does not rest unfilled market orders",()=>{const book=new MatchingEngine();const result=book.submit({side:"buy",quantity:2,orderType:"market"});expect(result.order.status).toBe("unfilled");expect(book.snapshot().bids).toHaveLength(0)});
  it("rejects duplicate IDs and invalid orders",()=>{const book=new MatchingEngine();book.submit({side:"buy",quantity:1,price:99,orderId:"x"});expect(()=>book.submit({side:"sell",quantity:1,price:101,orderId:"x"})).toThrow("Duplicate");expect(()=>book.submit({side:"buy",quantity:0,price:99})).toThrow("Quantity")});
  it("matches the shared Python parity fixture",()=>{const book=new MatchingEngine();for(const action of fixture.actions)book.submit({side:action.side as "buy"|"sell",quantity:action.quantity,price:action.price,orderId:action.orderId});expect(book.trades.map(({price,quantity,maker,taker})=>({price,quantity,maker,taker}))).toEqual(fixture.expectedTrades);const ask=book.snapshot().asks[0];expect({price:ask.price,remaining:ask.remaining,orderId:ask.orderId}).toEqual(fixture.expectedAsk)});
});
